_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 55
                - 95
                - 105
            "2":
                - 55
                - 95
                - 105
            "3":
                - 23
                - 55
            "4": 3.11.0
            "5": 0.19.10
            "8":
                - 3
                - 5
            "12": 0.19.10
            "13": windows-amd64
