_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 55
                - 95
                - 105
            "2":
                - 55
                - 95
                - 105
            "3":
                - 23
                - 55
            "4": 3.10.11
            "5": 0.19.9
            "8":
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
